### ISSUE TITLE
clientImportedModules use cases

### ISSUE THREAD

**Issue by guybedford** [capaj/jspm-hot-reloader#19]
I'm just trying to understand why `clientImportedModules` needs to be tracked at all. Surely the natural parent analysis process would cover these exact modules? In what scenarios does this apply?

**Comment by capaj** [comment]
I introduced those after working on the cyclic dependency case. For my test setup with react, if you have a cyclic chain of deps, you end up with a situation where you know you should call System.import, but it is unclear on which one, because there is no root.
So I introduced `clientImportedModules` modules. Because in most usecases like react/mithrill/angular you would want to reimport the same modules on a change of any modules.

**Comment by guybedford** [comment]
Yes the hot reloader should design its top-level `System.import` calls to maintain the natural execution order of the tree. Tracking System.import as the source of truth here then makes complete sense!
